services:
  - type: web
    name: tamtom-api
    runtime: node
    repo: https://github.com/nmtrhyb-cloud/tamtomnewupdat
    plan: starter
    region: oregon
    buildCommand: |
      rm -rf node_modules package-lock.json
      npm cache clean --force
      npm install --registry=https://registry.npmjs.org
      npm run build
    startCommand: npm start
    envVars:
      - key: NPM_CONFIG_REGISTRY
        value: https://registry.npmjs.org
      - key: NODE_ENV
        value: production
