services:
  - type: web
    name: tamtomnewupdat
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.22.0
      - key: NPM_CONFIG_REGISTRY
        value: https://registry.npmjs.org/
